In [1]:
%run pretrain.py

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\SLEEPY~1\AppData\Local\Temp\jieba.cache
Loading model cost 1.363 seconds.
Prefix dict has been built successfully.


the latest pre-trained model is pre_trained_65.pkl


c:\Users\Sleepyard\miniconda3\envs\d2l\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


encoder输入: ['用', '音乐', '来', '灌醉', '你']
decoder输入: ['<go>', '你', '就是', '海滩', '下', '那', '的', '乌', '克', '丽丽', '<eos>']
target目标: ['你', '就是', '海滩', '下', '那', '的', '乌', '克', '<unk>', '<eos>']
预测结果: ['我', '是', '海滩', '你', '过', '的', '乌', '克', '<eos>', '<eos>']
attention:
 tensor([[6.0580e-02, 6.8272e-03, 5.4618e-04, 1.8878e-01, 7.4326e-01],
        [1.8312e-04, 7.1510e-04, 5.2871e-03, 5.5486e-01, 4.3896e-01],
        [4.3742e-01, 2.7922e-01, 2.9881e-02, 1.6357e-01, 8.9908e-02],
        [8.8267e-02, 1.3518e-02, 5.9371e-02, 8.1810e-02, 7.5703e-01],
        [8.1265e-03, 1.5040e-02, 2.3202e-03, 1.0928e-01, 8.6524e-01],
        [3.7515e-02, 1.0766e-01, 1.3278e-02, 3.2054e-01, 5.2100e-01],
        [5.6107e-02, 1.0699e-01, 7.7887e-03, 4.3476e-02, 7.8564e-01],
        [1.5016e-01, 4.1788e-01, 1.1053e-02, 6.1271e-02, 3.5963e-01],
        [1.6342e-02, 3.0133e-01, 1.7151e-02, 5.6748e-02, 6.0843e-01],
        [6.2812e-02, 1.0233e-01, 1.0939e-02, 6.5414e-02, 7.5851e-01],
        [7.1934e-03, 1.1691e-02, 1.

In [2]:
%run supervc.py

fine tune:果味VC
the latest pre-trained model is pre_trained_100.pkl
current lr: 0.00049
encoder输入: ['今天', '是', '我', '仅', '有', '的', '时间']
decoder输入: ['<go>', '只', '想', '让', '你', '看见', '<eos>']
target目标: ['只', '想', '让', '你', '看见', '<eos>']
预测结果: ['就', '怪', '给', '我', '走进', '<eos>']
attention:
 tensor([[1.4539e-01, 4.5323e-01, 9.8325e-02, 6.8567e-02, 7.8672e-02, 9.4255e-02,
         6.1564e-02],
        [2.1552e-01, 2.8486e-02, 2.5662e-02, 4.0326e-04, 1.8938e-03, 2.1950e-02,
         7.0608e-01],
        [1.0507e-01, 1.1845e-01, 1.4266e-01, 1.1328e-02, 8.0684e-02, 1.1004e-01,
         4.3178e-01],
        [3.0657e-01, 2.6326e-02, 8.1965e-02, 2.5562e-02, 5.6993e-02, 1.9656e-01,
         3.0602e-01],
        [8.6273e-02, 4.2171e-01, 2.8374e-02, 1.3539e-02, 9.2261e-02, 1.6900e-01,
         1.8885e-01],
        [4.7399e-01, 1.0125e-01, 1.0375e-02, 9.7308e-04, 1.4167e-02, 2.1560e-02,
         3.7768e-01],
        [6.1339e-01, 2.1209e-01, 1.2599e-02, 8.0403e-04, 4.3212e-03, 7.1483e-02,
         8

In [1]:
%run finetune.py

fine tune:邓丽君


Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\SLEEPY~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.853 seconds.
Prefix dict has been built successfully.


the latest pre-trained model is pre_trained_100.pkl
current lr: 0.00049


c:\Users\Sleepyard\miniconda3\envs\d2l\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


encoder输入: ['飞翔', '呀', '飞翔']
decoder输入: ['<go>', '飞', '在', '蓝天', '上', '<eos>']
target目标: ['飞', '在', '蓝天', '上', '<eos>']
预测结果: ['飞', '在', '原野', '上', '<eos>']
attention:
 tensor([[9.0089e-03, 2.8596e-04, 9.9071e-01],
        [5.4079e-02, 5.0684e-02, 8.9524e-01],
        [3.3382e-02, 2.4813e-02, 9.4181e-01],
        [1.9501e-01, 1.2797e-01, 6.7701e-01],
        [8.9923e-01, 2.5456e-02, 7.5313e-02],
        [8.0023e-01, 1.3270e-02, 1.8650e-01]], grad_fn=<SelectBackward0>)
epoch 0 step 5 loss: 2.7469042778015136
epoch 0 step 10 loss: 2.220359373092651
epoch 0 step 15 loss: 2.250010633468628
epoch 0 step 20 loss: 2.214658784866333
epoch 0 step 25 loss: 2.2631035327911375
epoch 0 step 30 loss: 2.1634090900421143
epoch 0 step 35 loss: 2.175160551071167
epoch 0 step 40 loss: 2.139564800262451
epoch 0 step 45 loss: 2.1763768672943113
epoch 1 step 5 loss: 2.3385539770126345
epoch 1 step 10 loss: 1.8997028827667237
epoch 1 step 15 loss: 1.936851191520691
epoch 1 step 20 loss: 1.9050029516220093
ep